apply plugin: 'com.android.library'
apply plugin: 'maven-publish'

ext.abiCodes = ["armeabi-v7a": 1, "arm64-v8a": 2, "x86": 3, "x86_64": 4]
ext.universalBase = 8000

version = "2.0.3"

android {
    namespace 'is.xyz.mpv'
    compileSdk = 36

    defaultConfig {
        minSdkVersion 24
        targetSdk = 36

        versionCode 42
        versionName version

        // Load information about the NDK to use
        def props = new Properties()
        def propfile = new File(rootDir, 'ndk.properties')
        if (propfile.exists())
            props.load(new FileInputStream(propfile))
        ndkVersion = props.getProperty('ndkVersion', '')
        ndkPath = props.getProperty('ndkRoot', '')
    }


    sourceSets {
        main {
            jniLibs.srcDirs = ['src/main/libs']
        }
    }

    buildFeatures {
        buildConfig = true
    }

    // https://youtrack.jetbrains.com/issue/KT-55947
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    tasks.withType(org.jetbrains.kotlin.gradle.tasks.KotlinCompile) {
        kotlinOptions.jvmTarget = JavaVersion.VERSION_17.toString()
    }

    publishing {
        singleVariant("release") {
            withSourcesJar()
        }
    }
}

afterEvaluate {
    publishing {
        publications {
            release(MavenPublication) {
                from components.release

                groupId = project.findProperty("GROUP") ?: "com.github.marlboro-advance"
                artifactId = "mpv-android"
                version = project.findProperty("VERSION") ?: project.version
            }
        }
    }
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"
    implementation 'androidx.appcompat:appcompat:1.7.1'
}
